PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO subjects (name, description, difficulty) VALUES
('Mathematics', 'Practice algebra, geometry, and reasoning problems.', 'Medium'),
('English', 'Improve comprehension, grammar, and vocabulary skills.', 'Easy'),
('Physics', 'Test core physics concepts and problem solving.', 'Hard'),
('Chemistry', 'Review chemical principles and equations.', 'Hard'),
('Biology', 'Practice biology topics from cells to ecology.', 'Medium'),
('Computer Science', 'Prepare for logic, algorithms, and programming basics.', 'Medium');

INSERT OR IGNORE INTO questions (subject_id, text, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty) VALUES
(1, 'What is the value of x when 2x + 5 = 17?', '5', '6', '11', '12', 'B', '2x + 5 = 17 means 2x = 12, so x = 6.', 'Easy'),
(1, 'If the angles of a triangle are x, 2x, and 3x, what is x?', '20°', '30°', '40°', '45°', 'B', 'The angles sum to 180°, so 6x = 180 and x = 30°.', 'Medium'),
(1, 'Solve for y: 3(y - 2) = 2y + 1.', '1', '3', '5', '7', 'D', '3y - 6 = 2y + 1 so y = 7.', 'Medium'),
(1, 'What is the slope of the line passing through (2, 3) and (5, 11)?', '2', '8/3', '3', '4', 'B', 'Slope = (11 - 3)/(5 - 2) = 8/3.', 'Medium'),
(1, 'What is 15% of 200?', '20', '25', '30', '35', 'C', '15% of 200 is 0.15 × 200 = 30.', 'Easy'),
(1, 'If f(x) = x^2 - 4x + 3, what are the roots?', '1 and 3', '2 and -2', '-1 and -3', '4 and -1', 'A', 'The quadratic factors as (x-1)(x-3), so roots are 1 and 3.', 'Medium'),
(1, 'What is the next number in the sequence 2, 5, 10, 17, ?', '20', '23', '24', '26', 'D', 'The pattern is n^2 + 1; the next term is 26.', 'Hard'),
(1, 'Simplify (3x^2)(2x^3).', '5x^5', '6x^5', '6x^6', '9x^6', 'B', 'Multiply coefficients and add exponents: 3*2=6 and x^2*x^3=x^5.', 'Medium'),
(1, 'If a rectangle has area 48 and width 6, what is its perimeter?', '20', '28', '26', '32', 'B', 'Length = 8, perimeter = 2(6 + 8) = 28.', 'Easy'),
(2, 'Which sentence is punctuated correctly?', 'I enjoy reading, writing and music.', 'I enjoy reading, writing, and music.', 'I enjoy reading writing and music.', 'I enjoy reading; writing and music.', 'B', 'Use commas in a list between items.', 'Easy'),
(2, 'Choose the word that best completes the sentence: The athlete felt __ after winning the race.', 'elated', 'distraught', 'anxious', 'complacent', 'A', 'Elated means extremely happy, which fits winning.', 'Easy'),
(2, 'Which sentence uses passive voice?', 'The chef cooked the meal.', 'The meal was cooked by the chef.', 'The chef is cooking the meal.', 'The meal cooks quickly.', 'B', 'Passive voice uses the object as the subject of the sentence.', 'Medium'),
(2, 'Identify the correct spelling.', 'Accomodate', 'Acommodate', 'Accommodate', 'Acommadate', 'C', 'Accommodate has two c''s and two m''s.', 'Easy'),
(2, 'Which word best replaces the phrase very tired?', 'content', 'exhausted', 'joyful', 'amazed', 'B', 'Exhausted means very tired.', 'Easy'),
(2, 'What is the meaning of the idiom break the ice?', 'Shatter a window', 'Start a conversation', 'Leave the room', 'Create a problem', 'B', 'It means to begin a conversation in a social setting.', 'Medium'),
(2, 'Choose the sentence with correct subject-verb agreement.', 'The team are winning.', 'The team is winning.', 'The team were winning.', 'The team be winning.', 'B', 'Team is a collective noun that takes singular agreement here.', 'Easy'),
(2, 'Which sentence contains a fragment?', 'She went to the store and bought milk.', 'Because it was raining.', 'They watched a movie.', 'The cat slept.', 'B', 'Because it was raining is a dependent clause and not a complete sentence.', 'Medium'),
(2, 'Select the best meaning of anticipation.', 'anger', 'hope', 'confusion', 'shortness', 'B', 'Anticipation means expecting something with excitement or anxiety.', 'Easy'),
(3, 'What is the net force on a 5 kg object accelerating at 4 m/s²?', '5 N', '10 N', '20 N', '25 N', 'C', 'Newton''s second law: F = ma = 5 × 4 = 20 N.', 'Easy'),
(3, 'A wave has a frequency of 5 Hz and a wavelength of 2 m. What is its speed?', '2.5 m/s', '5 m/s', '7.5 m/s', '10 m/s', 'D', 'Speed = frequency × wavelength = 5 × 2 = 10 m/s.', 'Medium'),
(3, 'Which form of energy is stored in a compressed spring?', 'Thermal', 'Kinetic', 'Potential', 'Light', 'C', 'A compressed spring stores elastic potential energy.', 'Easy'),
(3, 'An object falls freely. Which quantity increases at a constant rate?', 'Mass', 'Velocity', 'Acceleration', 'Momentum', 'C', 'In free fall, acceleration due to gravity stays constant near Earth''s surface.', 'Medium'),
(3, 'What kind of mirror is used to focus sunlight to a point?', 'Plane', 'Convex', 'Concave', 'Cylindrical', 'C', 'A concave mirror converges light to a focal point.', 'Easy'),
(3, 'Which particle has a negative charge?', 'Proton', 'Neutron', 'Electron', 'Alpha particle', 'C', 'Electrons carry a negative charge.', 'Easy'),
(3, 'If a 10 N force pushes an object 3 m, how much work is done?', '3 J', '10 J', '13 J', '30 J', 'D', 'Work = force × distance = 10 × 3 = 30 J.', 'Medium'),
(3, 'What is the momentum of a 2 kg object moving at 5 m/s?', '2.5 kg·m/s', '5 kg·m/s', '7 kg·m/s', '10 kg·m/s', 'D', 'Momentum = mass × velocity = 2 × 5 = 10 kg·m/s.', 'Medium'),
(3, 'What is the period of a pendulum that completes 20 swings in 40 seconds?', '0.5 s', '1 s', '2 s', '4 s', 'C', 'Period = total time / number of swings = 40 / 20 = 2 s.', 'Hard'),
(4, 'What is the chemical symbol for sodium?', 'Na', 'S', 'N', 'So', 'A', 'Sodium is represented by Na.', 'Easy'),
(4, 'Which pH value is acidic?', '2', '7', '9', '11', 'A', 'Acidic solutions have pH below 7.', 'Easy'),
(4, 'What is the product of hydrochloric acid and sodium hydroxide?', 'Water and salt', 'Water and oxygen', 'Hydrogen gas', 'Sodium metal', 'A', 'A neutralization reaction produces water and salt.', 'Medium'),
(4, 'How many protons are in carbon-12?', '6', '12', '18', '24', 'A', 'Carbon-12 has 6 protons.', 'Easy'),
(4, 'Which element is a noble gas?', 'Oxygen', 'Nitrogen', 'Argon', 'Chlorine', 'C', 'Argon is a noble gas in group 18.', 'Easy'),
(4, 'What type of bond forms when electrons are shared?', 'Ionic', 'Covalent', 'Metallic', 'Hydrogen', 'B', 'Covalent bonds involve shared electrons.', 'Medium'),
(4, 'Which gas is produced in photosynthesis?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen', 'A', 'Photosynthesis releases oxygen as a byproduct.', 'Medium'),
(4, 'What is the oxidation state of oxygen in H2O?', '-1', '0', '-2', '+1', 'C', 'Oxygen has oxidation state -2 in water.', 'Hard'),
(5, 'Which cell structure contains genetic information?', 'Mitochondrion', 'Ribosome', 'Nucleus', 'Chloroplast', 'C', 'The nucleus stores DNA in eukaryotic cells.', 'Easy'),
(5, 'What process do plants use to make food?', 'Respiration', 'Photosynthesis', 'Digestion', 'Fermentation', 'B', 'Photosynthesis converts light energy into chemical energy.', 'Easy'),
(5, 'What is the largest organ in the human body?', 'Heart', 'Liver', 'Skin', 'Brain', 'C', 'The skin is the largest organ by surface area.', 'Easy'),
(5, 'Which blood cells carry oxygen?', 'White blood cells', 'Red blood cells', 'Platelets', 'Stem cells', 'B', 'Red blood cells transport oxygen using hemoglobin.', 'Easy'),
(5, 'What is the function of the mitochondria?', 'Protein production', 'Energy production', 'DNA replication', 'Hormone secretion', 'B', 'Mitochondria are the cell''s powerhouses.', 'Medium'),
(5, 'Which structure makes proteins?', 'Nucleus', 'Ribosome', 'Golgi apparatus', 'Lysosome', 'B', 'Ribosomes synthesize proteins.', 'Easy'),
(5, 'What do enzymes do?', 'Slow reactions', 'Store energy', 'Speed up reactions', 'Create sugars', 'C', 'Enzymes lower activation energy to speed reactions.', 'Medium'),
(5, 'Which term describes all the living organisms in an area?', 'Population', 'Community', 'Ecosystem', 'Biosphere', 'B', 'A community includes all populations living together.', 'Hard'),
(6, 'Which data structure uses FIFO order?', 'Stack', 'Queue', 'Tree', 'Graph', 'B', 'A queue processes items first in, first out.', 'Easy'),
(6, 'What does HTML stand for?', 'Hyperlink Text Markup Language', 'Hypertext Markup Language', 'Hypertext Markdown Language', 'Hyperlink Metadata Language', 'B', 'HTML stands for Hypertext Markup Language.', 'Easy'),
(6, 'Which language is used for styling web pages?', 'HTML', 'Python', 'JavaScript', 'CSS', 'D', 'CSS is used to style HTML pages.', 'Easy'),
(6, 'What is the correct syntax to call a function named greet in JavaScript?', 'call greet()', 'greet()', 'function greet()', 'invoke greet()', 'B', 'Functions are called by using their name followed by parentheses.', 'Easy'),
(6, 'Which keyword declares a constant in JavaScript?', 'let', 'var', 'const', 'static', 'C', 'const declares a constant variable in JavaScript.', 'Medium'),
(6, 'What is the binary equivalent of decimal 5?', '0101', '1010', '1111', '0011', 'A', 'Binary 0101 equals decimal 5.', 'Easy'),
(6, 'Which algorithmic concept finds the best solution among many?', 'Sorting', 'Searching', 'Optimization', 'Recursion', 'C', 'Optimization chooses the best solution.', 'Medium'),
(6, 'What does CPU stand for?', 'Central Process Unit', 'Central Processing Unit', 'Computer Processing Unit', 'Core Processing Unit', 'B', 'CPU stands for Central Processing Unit.', 'Medium');
